/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// Minimal C-Next fixture for activation tests
uint8_t counter = 0;

void increment(void) {
    counter = counter + 1;
}
