export const DIAGNOSTIC_DEBOUNCE_MS = 300;
export const EDITOR_SWITCH_DEBOUNCE_MS = 150;
export const CACHE_CLEANUP_INTERVAL_MS = 5 * 60 * 1000;
export const MAX_GLOBAL_COMPLETION_ITEMS = 30;
export const MIN_PREFIX_LENGTH_FOR_CPP_QUERY = 2;
